function report = check_matlab_env(features)
%CHECK_MATLAB_ENV 按选中的模型功能动态检查 MATLAB 工具箱。
arguments
    features (1,:) string
end

mapping = struct( ...
    'data', "MATLAB", ...
    'visualization', "MATLAB", ...
    'optimization', "Optimization Toolbox", ...
    'integer_optimization', "Optimization Toolbox", ...
    'statistics', "Statistics and Machine Learning Toolbox", ...
    'machine_learning', "Statistics and Machine Learning Toolbox", ...
    'time_series', "Econometrics Toolbox", ...
    'graph', "MATLAB", ...
    'symbolic', "Symbolic Math Toolbox");

versionInfo = ver;
installed = string({versionInfo.Name});
required = strings(0);
unknown = strings(0);
for feature = features
    key = strrep(feature, "-", "_");
    if ~isfield(mapping, char(key))
        unknown(end + 1) = feature; %#ok<AGROW>
    else
        required(end + 1) = mapping.(key); %#ok<AGROW>
    end
end
required = unique(required);
missing = required(~ismember(required, installed));

report = struct( ...
    'ok', isempty(missing) && isempty(unknown), ...
    'matlab_version', version, ...
    'features', features, ...
    'required_toolboxes', required, ...
    'missing_toolboxes', missing, ...
    'unknown_features', unknown);
disp(jsonencode(report, 'PrettyPrint', true));
end
